<script setup>
import { computed } from 'vue'
import { useLocale } from '../composables/useLocale'

const { locale } = useLocale()

const guarantees = computed(() => {
  if (locale.value === 'ja') {
    return [
      { label: '決定論', note: '同一入力なら同一の認可結果' },
      { label: 'Fail-Closed', note: '不確実時に PROCEED を返さない' },
      { label: '明示責任', note: 'ACK は範囲付きで追跡可能' },
      { label: '監査可能性', note: '証跡を既定で生成' },
    ]
  }

  return [
    { label: 'Deterministic', note: 'Same input -> same authorization output' },
    { label: 'Fail-Closed', note: 'Uncertainty never defaults to PROCEED' },
    { label: 'Explicit Responsibility', note: 'Acknowledgment is scoped and traceable' },
    { label: 'Auditability', note: 'Evidence generated by default' },
  ]
})

const nonClaims = computed(() => {
  if (locale.value === 'ja') {
    return ['予測エンジンではない', '意思決定最適化ではない', 'ドメイン正しさは保証しない', 'リスク消滅を約束しない']
  }

  return [
    'No prediction engine',
    'No decision optimizer',
    'No domain-correctness claim',
    'No risk elimination claim',
  ]
})

const copy = computed(() => {
  if (locale.value === 'ja') {
    return {
      eyebrow: 'コア',
      title: '中核保証',
      guaranteed: '保証',
      nonClaims: '明示的な非保証',
    }
  }

  return {
    eyebrow: 'Core',
    title: 'Core Guarantees',
    guaranteed: 'Guaranteed',
    nonClaims: 'Explicit Non-Claims',
  }
})
</script>

<template>
  <section id="core-guarantees" class="section reveal fade-up">
    <div class="section-head">
      <p class="eyebrow">{{ copy.eyebrow }}</p>
      <h2>{{ copy.title }}</h2>
    </div>
    <div class="three-grid compact-grid">
      <article
        v-for="(item, idx) in guarantees"
        :key="item.label"
        class="card guarantee-tile reveal fade-up"
        :style="{ '--reveal-delay': `${idx * 70}ms` }"
      >
        <p class="tile-kicker">{{ copy.guaranteed }}</p>
        <h3>{{ item.label }}</h3>
        <p>{{ item.note }}</p>
      </article>
      <article class="card reveal fade-in non-claims">
        <h3>{{ copy.nonClaims }}</h3>
        <ul>
          <li v-for="item in nonClaims" :key="item">{{ item }}</li>
        </ul>
      </article>
    </div>
  </section>
</template>

