<script setup>
const guarantees = [
  { label: 'Deterministic', note: 'Same input -> same authorization output' },
  { label: 'Fail-Closed', note: 'Uncertainty never defaults to PROCEED' },
  { label: 'Explicit Responsibility', note: 'Acknowledgment is scoped and traceable' },
  { label: 'Auditability', note: 'Evidence generated by default' },
]

const nonClaims = [
  'No prediction engine',
  'No decision optimizer',
  'No domain-correctness claim',
  'No risk elimination claim',
]
</script>

<template>
  <section id="core-guarantees" class="section reveal fade-up">
    <div class="section-head">
      <p class="eyebrow">Core</p>
      <h2>Core Guarantees</h2>
    </div>
    <div class="three-grid compact-grid">
      <article
        v-for="(item, idx) in guarantees"
        :key="item.label"
        class="card guarantee-tile reveal fade-up"
        :style="{ '--reveal-delay': `${idx * 70}ms` }"
      >
        <p class="tile-kicker">Guaranteed</p>
        <h3>{{ item.label }}</h3>
        <p>{{ item.note }}</p>
      </article>
      <article class="card reveal fade-in non-claims">
        <h3>Explicit Non-Claims</h3>
        <ul>
          <li v-for="item in nonClaims" :key="item">{{ item }}</li>
        </ul>
      </article>
    </div>
  </section>
</template>

