<script setup>
import { computed } from 'vue'
import { useLocale } from '../composables/useLocale'

const { locale } = useLocale()

const guarantees = computed(() => {
  if (locale.value === 'ja') {
    return [
      { label: '決定論', note: '同一入力なら同一の認可結果' },
      { label: 'Fail-Closed', note: '不確実時に PROCEED を返さない' },
      { label: '明示責任', note: 'ACK は範囲付きで追跡可能' },
      { label: '監査可能性', note: '証跡を既定で生成' },
    ]
  }

  return [
    { label: 'Deterministic', note: 'Same input -> same authorization output' },
    { label: 'Fail-Closed', note: 'Uncertainty never defaults to PROCEED' },
    { label: 'Explicit Responsibility', note: 'Acknowledgment is scoped and traceable' },
    { label: 'Auditability', note: 'Evidence generated by default' },
  ]
})

const nonClaims = computed(() => {
  if (locale.value === 'ja') {
    return ['予測エンジンではない', '意思決定最適化ではない', 'ドメイン正しさは保証しない', 'リスク消滅を約束しない']
  }

  return [
    'No prediction engine',
    'No decision optimizer',
    'No domain-correctness claim',
    'No risk elimination claim',
  ]
})

const copy = computed(() => {
  if (locale.value === 'ja') {
    return {
      eyebrow: 'コア',
      title: '中核保証',
      guaranteed: 'Invariant',
      nonClaims: '明示的な非保証',
      lead: '実行境界で妥協しない 4 つの不変条件',
    }
  }

  return {
    eyebrow: 'Core',
    title: 'Core Guarantees',
    guaranteed: 'Invariant',
    nonClaims: 'Explicit Non-Claims',
    lead: 'Four non-negotiable invariants at the execution boundary',
  }
})
</script>

<template>
  <section id="core-guarantees" class="section section-tone-guarantees reveal fade-up guarantee-section">
    <div class="section-head">
      <p class="eyebrow">{{ copy.eyebrow }}</p>
      <h2>{{ copy.title }}</h2>
    </div>
    <div class="card card-tint-teal guarantee-lead reveal fade-in">
      <p class="tile-kicker">{{ copy.guaranteed }}</p>
      <h3>{{ copy.lead }}</h3>
    </div>
    <div class="guarantee-grid">
      <article
        v-for="(item, idx) in guarantees"
        :key="item.label"
        class="card card-tint-teal guarantee-strong reveal fade-up"
        :class="`tone-${idx + 1}`"
        :style="{ '--reveal-delay': `${idx * 70}ms` }"
      >
        <p class="guarantee-index mono">0{{ idx + 1 }}</p>
        <p class="tile-kicker">{{ copy.guaranteed }}</p>
        <h3>{{ item.label }}</h3>
        <p>{{ item.note }}</p>
      </article>
    </div>
    <article class="card card-tint-amber reveal fade-in guarantee-nonclaims">
      <h3>{{ copy.nonClaims }}</h3>
      <div class="chip-list">
        <span v-for="item in nonClaims" :key="item" class="chip chip-muted">{{ item }}</span>
      </div>
    </article>
  </section>
</template>

